version: "3.3"

services:
  wt-frontend:
    build:
      context: ./wt-frontend
    environment:
      - CHOKIDAR_USERPOLLING=true
    ports:
      - 3000:3000
    container_name: wt-frontend
    stdin_open: true
    volumes:
      - ./wt-frontend:/usr/src/app/wt-frontend
      - /usr/src/app/wt-frontend/node_modules

  wt-database:
    container_name: wt-database
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=worktravel
      - MYSQL_USER=erasmus
      - MYSQL_PASSWORD=erasmus
      - MYSQL_ROOT_PASSWORD=erasmus
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./.mysql-data/db:/var/lib/mysql

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 30s
      timeout: 10s
      # start_period: 30s
      retries: 5

  messagebroker:
    container_name: messagebroker
    build:
      context: ./messagebroker
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - /usr/src/app/messagebroker

  wt-backend:
    container_name: wt-backend
    build:
      context: ./wt-backend
    ports:
      - 8080:8080
    # restart: on-failure
    depends_on:
      wt-database:
        condition: service_started
      messagebroker:
        condition: service_started
